[package]
name = "tdrop"
description="A crate providing widgets, layout, and styling for non-TUI applications"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
terminal-light = "1.8.0"
unicode-segmentation = "1.12.0"
unicode-truncate = "2.0.0"
unicode-width = "0.2.1"
