[package]
name = "tdrop"
description="A crate providing widgets, layout, and styling for non-TUI applications"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.4"
crossterm = "0.29.0"
document-features = "0.2.11"
unicode-segmentation = "1.12.0"
unicode-width = "0.2.1"
